spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/mybatis_plus
    username: root
    password: 123

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted